### ISSUE TITLE
How to launch custom APK in Paper Pro

### ISSUE THREAD

**Issue by WillyYeh** [rbx-rdm/documentation#1]
We want to run our mooInk apk on Paper Pro.
Please give us an instruction to describe how to do it officially.
Many thanks.

**Comment by namenu** [comment]
Hello Willy,

We''ll write up an instruction shortly.

**Comment by YSYoon** [comment]
Hello @WillyYeh ,

I've just uploaded brief instruction on how to enable ADB on your device.
[[link](https://github.com/rbx-rdm/documentation/blob/master/rom/README.md#enable-adb-on-user-build-device)]

After enabling ADB on your device, you should be able to use adb commands to install and run your application.

Ridibooks PAPER PRO was not originally designed for installing or running external applications so there will be limited functionality (no recent app menu, no list of installed app, etc)

Maybe you can use adb root to gain root permission, install third party launcher app and then remove /system/app/com.ridi.paper.apk .

You should also note that there are some bugs in Settings app in the menus that Ridi does not use.


Please let me know if provided instructions seem unclear or if you need more information / support.


Thank you.

**Comment by ender503** [comment]
Hi @YSYoon ,

I've just follow the instruction and get these error message: 

```shell
$ sh setup.sh
rm: out/target/product/ntx_6sl/system/build.prop: No such file or directory
Version [x.x(.x)] : 1.0.2P
Extra code (can be empty) :
Version date code [yyyymmddxx] : 20180409

$ sh fastboot.sh
cat: /Users/than/Source/Ridibooks/pp1/.model: No such file or directory
cat: /Users/than/Source/Ridibooks/pp1/.model: No such file or directory
cat: /Users/than/Source/Ridibooks/pp1/.model: No such file or directory
fastboot.sh: line 202: syntax error near unexpected token `>'
fastboot.sh: line 202: `    sudo ${ANDROID_HOST_TOOL_PATH}/adb shell "./system/bin/busybox dd if=/dev/zero of=/dev/block/mmcblk0 bs=512 seek=1536 count=256" &>> ${TEMP_FILE_PATH}/fb.log'

```

My enviorment is macOS 10.13.3.

Should I build the the source code [[link](https://github.com/rbx-rdm/documentation)] before following these instruction? 🤔

**Comment by YSYoon** [comment]
Hi @sephXD ,

As mentioned in the main document of this repository, recommended environment is Ubuntu 12.04 which uses case-sensitive file system - whereas macOS uses case insensitive file system, making it impossible to build Android OS. I think you will need at lease one Ununtu PC to build and test firmware yourself (it is possible to change macOS file system to case-seisitive one, but not really recommended)

The error is probably occurring because the script was created for Ubuntu environment. Maybe I can make some changes to make it work in macOS environment as well, but in the end you'll need to setup Ubuntu PC for building firmware.

If you just wish to enable ADB on the device, I'll go over the script and see if it can be made macOS friendly, let me know if that's what you need right now.

**Comment by ender503** [comment]
Hi @YSYoon ,

> As mentioned in the main document of this repository, recommended environment is Ubuntu 12.04 which uses case-sensitive file system - whereas macOS uses case insensitive file system, making it impossible to build Android OS. I think you will need at lease one Ununtu PC to build and test firmware yourself (it is possible to change macOS file system to case-seisitive one, but not really recommended)

I'll find another Ubuntu PC to build and test firmware. 😃 

In order to test our app compatibility, I just want to enable ADB on the device for now.
Please make the script macOS friendly. Thanks for your help 👍

**Comment by YSYoon** [comment]
@sephXD 

Sorry for the delayed response, I've made some changes to the script but I am unable to connect the device to my MacBook. I am not sure if the updated script will work on your MacBook. (Scripts have only been tested on Ubuntu PC and Windows PC - script for Windows will be added later after translation is done)

As a side note, the script mentioned in the [documentation](https://github.com/rbx-rdm/documentation/blob/master/rom/README.md) is included in `develop` branch of pp1 repository.

I'll do some more tests on one of my co-workers MacBook and comment again before the end of the day. Thank you.

**Comment by YSYoon** [comment]
Still need more time to test on macOS. We'll get back to you on this tomorrow. Thank you.

**Comment by ender503** [comment]
Hi @YSYoon , 

I find another Ubuntu PC and try both instructions.

### Building firmware

First I try to build the building firmware with instuction [[link](https://github.com/rbx-rdm/documentation#building-firmware)].

In the section `Build Android firmware`, and run the command: 

```
$./build_android_img.sh android-userdebug
```

It comes up with following message, which password should I provide?

```
Please enter password for `platform.key`:
```

### Enable ADB on user build device

Then I try to enable ADB on user build device with the instrunction [[link](https://github.com/rbx-rdm/documentation/blob/master/rom/README.md#enable-adb-on-user-build-device)].

I make a mistake last time in step 2, I run the wrong command `./fastboot.sh`.

I should run the command `./fastboot_pcc.sh`, but I cannot find this command on the `pp1` repository.

**Comment by YSYoon** [comment]
@sephXD 
platform.key password is `android`

`rom/fastboot_pcc.sh` is included in `develop` branch of pp1 repository.
It has not been merged to `master` branch yet.

**Comment by ender503** [comment]
@YSYoon

#### Enable ADB on user build device

I followed the instrunction[[link](https://github.com/rbx-rdm/documentation/blob/master/rom/README.md#enable-adb-on-user-build-device)].
After finished these steps. I still cannot find my device with ADB command `adb devices`. :thinking_face
How can I do to turn on the ADB? Thanks for your help ;smily

```
readmoo@readmoo:~/pp1/rom$ ./fastboot_pcc.sh 
1. Flash all firmware (WIPE DATA, no ADB)
2. Flash all firmware (WIPE DATA, ADB enabled)
3. Flash system image (no ADB)
4. Flash system image (ADB enabled)
5. Flash serial number
q. Quit

Select menu (q to quit): 4   
PATH = /usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/jdk1.6.0_45/bin/:.
---> Please connect to device through USB!, then enter fastboot mode
       Wait device enter fastboot mode
[sudo] password for readmoo: 
       Device fastboot mode ready...
---> Device fastboot mode ready
---> In fastboot_get_display_resolution
DISPLAY_RESOLUTION = 1872x1404
---> In fastboot_get_PCBA
FRONTLIGHT_LED=0x04 
WIFI=0x08
PCBA=E70Q12
DISPLAY_RESOLUTION=1872x1404
********PCBA=E70Q12 ********
---> In fastboot_get_RAMType
RAMType = DDR3
---> Please connect to device through USB!, then enter fastboot mode
       Wait device enter fastboot mode
       Device fastboot mode ready...
---> Device fastboot mode ready
---> Programming uboot -------------------------------------------------
-rwxrwxr-x 1 readmoo readmoo 235832 Feb 20 11:24 /home/readmoo/pp1/rom/image_adb/u-boot_E70Q12.bin
       <bootloader> download and burn
       Please wait...	
       <bootloader> burn Done
---> Programming partition SYSTEM --------------------------------------
/home/readmoo/pp1/rom/image_adb/system.img
       <system> download and burn
       Please wait...	\ 
       <system> burn Done
1. Flash serial number
2. Flash waveform
3. Reboot (finish)

Select menu: 3
---> Reboot deviceBM6875-BM6675-BP6375
---> Finished -----------------------------
readmoo@readmoo:~/pp1/rom$ adb devices
List of devices attached 

readmoo@readmoo:~/pp1/rom$
```

**Comment by YSYoon** [comment]
@sephXD 
I've made some changes to `develop` branch of pp1 repository.
The procedure in the documentation should work now.

pp1 submodule reference has been updated too, to correctly point to repositories in rbx-rdm team. (you should run `git submodule update` after pulling. if anything goes wrong, please let me know)

**Comment by namenu** [comment]
Hi, @ender503 .
Nice to talk to you.

Is there any other difficulties to proceed?
If so, please feel free to ask us. 😊

**Comment by ender503** [comment]
Sorry for the delayed response. I just got the devices for developers yesterday.

Now I can connect to device's ADB, and run our app smoothly. 🎉 🎉 🎉 

But I have some question. 🤔 

 1. How to get the key event of the right-side custom button?

 2. How to set the brightness and CTM value?

 3. How to upgrade the system? Can we build our own `update.zip` to upgrade the Ridibooks system? If I download this `update.zip`, how to trigger the system upgrade process?

 4. If I build new app's apk, how to upgrade our app with your `PackageInstaller`?

 5. Can we use your screen lock instead of system setting provide? The system screen lock looks terriable.

 System screen lock: 

![img_3867](https://user-images.githubusercontent.com/1849431/38978168-26f1c5f6-43e9-11e8-9f45-b53e6f1b8277.JPG)

**Comment by namenu** [comment]
Nice!

I've issued the questions you asked #3 #4 #5 #6 .

Let's tackle one by one.

**Comment by ender503** [comment]
Thanks @namenu 😃

**Comment by AaronDewes** [comment]
Hi @namenu and @YSYoon,

many of the links in this repo don't work anymore, and many code seems to be missing. Is there any chance you could reupload it or link to an archive? 

I found this software interesting, and I'm personally using a ebook reader which seems to have a firmware similar to this one or based on this one, and having the original code would be interested.

If that's possible for you or there is an archive somewhere, please tell me. Thanks in advance!
