### ISSUE TITLE
Setup the system default language

### ISSUE THREAD

**Issue by WillyYeh** [rbx-rdm/documentation#11]
How to set system default language?

**Comment by YSYoon** [comment]
Hello @WillyYeh ,

Please see [/build/tools/buildinfo.sh](https://github.com/rbx-rdm/pp1/blob/ba42f8f64bf320ee012e66900d6b4889a88f2383/build/tools/buildinfo.sh#L34)

You can also add/remove default SystemProperty and other configuration there
