### ISSUE TITLE
MTP protocol not work properly

### ISSUE THREAD

**Issue by WillyYeh** [rbx-rdm/documentation#12]
Transfer file from PC to Paper Pro with MTP protocol will fail.

**Comment by YSYoon** [comment]
Hello @WillyYeh , 

Does it always fail? or just first few times upon first boot?

**Comment by WillyYeh** [comment]
If we transfer larger files into Paper Pro, the transfer process may fail suddenly.

**Comment by YSYoon** [comment]
@WillyYeh 

Netronix told us the internal storage is somewhat busy upon first boot, and may not be completely responsive for a while.

If this is not what you're experiencing, please provide more information:
- how large is the file?
- does it work fine for smaller files?
- what kind of OS and mtp client/software you are using,
- any other information that might help us reproduce the problem
