### ISSUE TITLE
How to change the animation for system reset process.

### ISSUE THREAD

**Issue by WillyYeh** [rbx-rdm/documentation#14]
If user reset system to factory mode,
an RIDI's animation came out.
We need to replace it to our own.

**Comment by YSYoon** [comment]
@WillyYeh 

### Background

The background animation is inside `/ntx_addon/system/media/bootanimation.zip`
- `desc.txt` contains information about the animation. format is as follows:
  - `width` `height` `framespersecond`
  - `repeat(c = play once)` `count(unused)` `pause(1)` `imagepath`
  - for more information see [BootAnimation.cpp](https://github.com/rbx-rdm/pp1-frameworks/blob/27480b1d4244903925f4d3d94e0b6fe422b5031c/base/cmds/bootanimation/BootAnimation.cpp#L431)
- `part0` contains actual background images (should match `imagepath` inside `desc.txt`

### Text

The text image files are inside `/bootable/recovery/res/images/`
For more information on how these images are used, see [screen_ui.cpp](https://github.com/rbx-rdm/pp1/blob/master/bootable/recovery/screen_ui.cpp)

**Comment by WillyYeh** [comment]
We changed boot animation, but reset to factory will show RIDI's.
I may record as video later.

**Comment by YSYoon** [comment]
@WillyYeh 

Oh sorry about that, I got cofused about that.

That Ridi image is `/bootable/recovery/res/images/icon_installing.png`

After changing the image file edit image position in [screen_ui.cpp:line161](https://github.com/rbx-rdm/pp1/blob/ba42f8f64bf320ee012e66900d6b4889a88f2383/bootable/recovery/screen_ui.cpp#L161)
