### ISSUE TITLE
How to set the brightness and CTM value

### ISSUE THREAD

**Issue by namenu** [rbx-rdm/documentation#3]

**Comment by YSYoon** [comment]
Setting or getting brightness is same as regular android OS:
```
ContentResolver resolver = getContentResolver();
int brightness = Settings.System.getInt(resolver, Settings.System.SCREEN_BRIGHTNESS);
Settings.System.putInt(resolver, Settings.System.SCREEN_BRIGHTNESS, brightness);
```

Color temperature is partially our custom implementation:
[link](https://github.com/rbx-rdm/pp1-frameworks/blob/27480b1d4244903925f4d3d94e0b6fe422b5031c/base/services/java/com/android/server/power/PowerManagerService.java#L2109)
Using these functions require `android.Manifest.permission.DEVICE_POWER`

Easiest method to access CTM functions would be to use reflection.

**Comment by ender503** [comment]
Thank you, got it. 👍
