### ISSUE TITLE
How to get the key event of the right-side custom button

### ISSUE THREAD

**Issue by namenu** [rbx-rdm/documentation#4]

**Comment by YSYoon** [comment]
1. Right-side custom key is currently mapped to `KeyEvent.KEYCODE_PROG_RED`
  This can be changed in `device/fsl/ntx_6sl/input/imx-keypad.kl`

2. **BUT** `KEYCODE_PROG_RED` is consumed by custom implementation and not passed to applications.
[link to code](https://github.com/rbx-rdm/pp1-frameworks/blob/27480b1d4244903925f4d3d94e0b6fe422b5031c/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java#L4246)
If you wish to use our implementation, 
receive `com.ridi.paper.ACTION.RUN_QUICK_ACTION` for click
receive `com.ridi.paper.ACTION.SHOW_QUICK_LAUNCHER` for long press.
If you wish to change our custom implementation, you can change the code linked above.
