### ISSUE TITLE
How to update the application / OS

### ISSUE THREAD

**Issue by namenu** [rbx-rdm/documentation#5]

**Comment by YSYoon** [comment]
Our current implementation adds a class to Settings App
[RidiUpdateReceiver.java](https://github.com/rbx-rdm/pp1-packages/blob/develop/apps/Settings/src/com/android/settings/update/RidiUpdateReceiver.java)

This class receives `com.ridi.paper.update.finish` with path string bundled as `update_img_path`.

If you wish to copy update.zip via mtp and install from adb shell, use following example:
`am broadcast -a "com.ridi.paper.update.finish" --es "update_img_path" "/cache/update.zip" -t "text/plain"`
change **/cache/update.zip** to the path and filename of your update file.

**Comment by ender503** [comment]
I'll do some test on it, I will reply you as soon as possible. 😃

**Comment by ender503** [comment]
Hi @YSYoon 
I've built the `update.zip`, and it's work fine.
By the way, is it possible to update the OS from the `/storage/extsd/` or `/storage/sdcard1/`? 🤔

**Comment by ender503** [comment]
When I use this command to update the device

```
$ am broadcast -a "com.ridi.paper.update.finish" --es "update_img_path" "/storage/sdcard1/update-1.0.2PRC2-2018043001.zip" -t "text/plain"
```

It comes up with this message

```
Finding update package...
E: failed to mount /mnt/media_rw/sdcard1 (No such file or directory)
E: Can’t mount /mnt/media/_rw/sdcard1/update-1.0.2PRC2-2018043001.zip
Installation: aborted.
```
