### ISSUE TITLE
How to change lock screen

### ISSUE THREAD

**Issue by namenu** [rbx-rdm/documentation#6]

**Comment by YSYoon** [comment]
We have not made any change to System lock screen, Ridi's lock screen is part of the application, not the system.

**Comment by YSYoon** [comment]
I think you should look into Keyguard App ([Keyguard](https://github.com/rbx-rdm/pp1-frameworks/tree/develop/base/packages/Keyguard))

**Comment by ender503** [comment]
Thanks, @YSYoon 
I'll look into this sample.

**Comment by WillyYeh** [comment]
Can we use your screen lock instead of system setting provide? 
The screen lock looks terrible that system setting provided.

**Comment by YSYoon** [comment]
Hello @WillyYeh ,

As we've already mentioned our lock screen is part of Ridi's application and not part of firmware. It would probably be more work for both of us to use Ridi's implementation in your firmware. I think it should be easier and faster to customize the Keyguard App as suggested above.

**Comment by WillyYeh** [comment]
How to add a reset flow for user who forgot Keyguard’s password.
For example, use a specified 4 digit number to make Keyguard run system reset process.

**Comment by YSYoon** [comment]
@WillyYeh 

Here's what Ridi's application does:

1. Keep last passcode entered
2. Check if last passcode and current passcode match the `magic code` (0331 in Ridi's case)
3. If yes, broadcast Intent `com.android.internal.os.storage.FORMAT_AND_FACTORY_RESET` with `ComponentName("android", "com.android.internal.os.storage.ExternalStorageFormatter")`
4. The Android OS will take care of the factory reset procedure

- We do not recommend making the `magic code` general knowledge.
