### ISSUE TITLE
How to change the Poweroff/Suspend images?

### ISSUE THREAD

**Issue by ender503** [rbx-rdm/documentation#9]
Hi @YSYoon 
I want to change the default Poweroff/Suspend images.
How can I do it? 🤔

**Comment by ender503** [comment]
I find out that the default images and suspend image are place in `ntx_addon/images`.

The `poweroff`, `powerlow` and `qsg` images seem to be place under the `packages/apps/MsgE6/res`, should I change the `MsgE6` app project directly?

**Comment by freekering** [comment]
Hi, @ender503.
@YSYoon is on holiday until May 4th. Maybe he will be able to check on May 8th. (May 7th is Korean official holiday.)
Thank you for your waiting.

**Comment by ender503** [comment]
Roger that. 
Thanks @freekering

**Comment by WillyYeh** [comment]
What is the recommended images’s format and size ?

**Comment by YSYoon** [comment]
@WillyYeh 

format: png or jpg
size: any 3:4 aspect ratio would be fine, or if you wnat pixel perfect quality use 1404px * 1872px
